<a href="https://colab.research.google.com/github/aniii052/DMPM-lab-24cseaiml052/blob/main/assignment_5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#to implement z-score normalization , min-max normalization & decimal scaling normalization on 10,20,30,40,50

In [1]:
import numpy as np
data = np.array([10, 20, 30, 40, 50], dtype=float)

mean = np.mean(data)

sd = np.std(data)

z_score = (data - mean) / sd

min_value = np.min(data)
max_value = np.max(data)

min_max = (data - min_value) / (max_value - min_value)

decimal_scaling = data / 100

print("Original Data:")
print(data)

print("\nZ-Score Normalization:")
print(z_score)

print("\nMin-Max Normalization:")
print(min_max)

print("\nDecimal Scaling Normalization:")
print(decimal_scaling)

Original Data:
[10. 20. 30. 40. 50.]

Z-Score Normalization:
[-1.41421356 -0.70710678  0.          0.70710678  1.41421356]

Min-Max Normalization:
[0.   0.25 0.5  0.75 1.  ]

Decimal Scaling Normalization:
[0.1 0.2 0.3 0.4 0.5]


In [ ]:
#to implement the decimal scaling normalization on a dataset(using kaggle dataset)

In [3]:
import pandas as pd
import numpy as np

data = pd.read_csv("Iris.csv")

x = data["PetalLengthCm"]

max_value = x.abs().max()

j = len(str(int(max_value)))

normalized = x / (10 ** j)

print("Original Values:")
print(x.head(10))

print("\nMaximum Value:", max_value)
print("Value of j:", j)

print("\nDecimal Scaling Normalized Values:")
print(normalized.head(10))

Original Values:
0    1.4
1    1.4
2    1.3
3    1.5
4    1.4
5    1.7
6    1.4
7    1.5
8    1.4
9    1.5
Name: PetalLengthCm, dtype: float64

Maximum Value: 6.9
Value of j: 1

Decimal Scaling Normalized Values:
0    0.14
1    0.14
2    0.13
3    0.15
4    0.14
5    0.17
6    0.14
7    0.15
8    0.14
9    0.15
Name: PetalLengthCm, dtype: float64


In [4]:
import pandas as pd

data = pd.read_csv("Iris.csv")

x = data["SepalWidthCm"]

minimum = x.min()
maximum = x.max()

normalized = (x - minimum) / (maximum - minimum)

print("Original Values:")
print(x.head(10))

print("\nMinimum Value:", minimum)
print("Maximum Value:", maximum)

print("\nMin-Max Normalized Values:")
print(normalized.head(10))

Original Values:
0    3.5
1    3.0
2    3.2
3    3.1
4    3.6
5    3.9
6    3.4
7    3.4
8    2.9
9    3.1
Name: SepalWidthCm, dtype: float64

Minimum Value: 2.0
Maximum Value: 4.4

Min-Max Normalized Values:
0    0.625000
1    0.416667
2    0.500000
3    0.458333
4    0.666667
5    0.791667
6    0.583333
7    0.583333
8    0.375000
9    0.458333
Name: SepalWidthCm, dtype: float64


In [5]:
import pandas as pd
import numpy as np

data = pd.read_csv("Iris.csv")

x = data["PetalWidthCm"]

mean = np.mean(x)

variance = np.var(x)

sd = np.std(x)

z_score = (x - mean) / sd

print("Mean =", mean)
print("Variance =", variance)
print("Standard Deviation =", sd)

print("\nOriginal Values:")
print(x.head(10))

print("\nZ-Score Normalized Values:")
print(z_score.head(10))

Mean = 1.1986666666666668
Variance = 0.5785315555555559
Standard Deviation = 0.760612618588172

Original Values:
0    0.2
1    0.2
2    0.2
3    0.2
4    0.2
5    0.4
6    0.3
7    0.2
8    0.2
9    0.1
Name: PetalWidthCm, dtype: float64

Z-Score Normalized Values:
0   -1.312977
1   -1.312977
2   -1.312977
3   -1.312977
4   -1.312977
5   -1.050031
6   -1.181504
7   -1.312977
8   -1.312977
9   -1.444450
Name: PetalWidthCm, dtype: float64
