<a href="https://colab.research.google.com/github/aniii052/DMPM-lab-24cseaiml052/blob/main/assignment_6.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import numpy as np
from sklearn.datasets import load_wine
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix

# Load Dataset
data = load_wine()
X, y = data.data, data.target

# Split Dataset
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)

# Scaling
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

# KNN
def knn(Xtr, ytr, Xte, k=3):
    result = []
    for x in Xte:
        d = np.sqrt(np.sum((Xtr - x) ** 2, axis=1))
        n = np.argsort(d)[:k]
        result.append(np.bincount(ytr[n]).argmax())
    return np.array(result)

# Prediction
y_pred = knn(X_train, y_train, X_test, 3)

# Output
print("========== KNN CLASSIFIER ==========")
print("Dataset        : Wine Dataset")
print("Total Samples  :", len(X))
print("Training Data  :", len(X_train))
print("Testing Data   :", len(X_test))
print("Number of Class:", len(np.unique(y)))
print("K Value        : 3")

print("\n========== PERFORMANCE ==========")
print("Accuracy  :", accuracy_score(y_test, y_pred))
print("Precision :", precision_score(y_test, y_pred, average="weighted"))
print("Recall    :", recall_score(y_test, y_pred, average="weighted"))
print("F1 Score  :", f1_score(y_test, y_pred, average="weighted"))

print("\n========== CONFUSION MATRIX ==========")
print(confusion_matrix(y_test, y_pred))


========== KNN CLASSIFIER ==========
Dataset        : Wine Dataset
Total Samples  : 178
Training Data  : 142
Testing Data   : 36
Number of Class: 3
K Value        : 3

========== PERFORMANCE ==========
Accuracy  : 0.9722222222222222
Precision : 0.9743589743589745
Recall    : 0.9722222222222222
F1 Score  : 0.9722633744855966

========== CONFUSION MATRIX ==========
[[12  0  0]
 [ 1 13  0]
 [ 0  0 10]]
